### ISSUE TITLE
About updating CTO in LEDBAT.py

### ISSUE THREAD

**Issue by utamaro** [justas-/PyPPSPP#1]
I'm trying to understand RFC7574.
PyPPSPP is very straight-forward implementation and it's very useful to understand.
Thanks.

BTW, there are some qeustions abou LEDBAT.py.

_update_cto():
```python
    def _update_cto(self):
        if self._first_est:
            self._srtt = self._qd
            self._rttvar = self._qd / 2
            self._cto = self._srtt + max([self._qd, LEDBAT.K * self._rttvar])
        else:
            self._rttvar = (1 - LEDBAT.BETA) * self._rttvar + LEDBAT.BETA * math.fabs(self._srtt - self._qd)
            self._srtt = (1 - LEDBAT.ALPHA) * self._srtt + LEDBAT.ALPHA * self._qd
            self._cto = self._srtt + max([self._g, LEDBAT.K * self._rttvar])
```

and   [RFC6298](https://tools.ietf.org/html/rfc6298) says:
```
   (2.2) When the first RTT measurement R is made, the host MUST set
            SRTT <- R
            RTTVAR <- R/2
            RTO <- SRTT + max (G, K*RTTVAR)
   (2.3) When a subsequent RTT measurement R' is made, a host MUST set
            RTTVAR <- (1 - beta) * RTTVAR + beta * |SRTT - R'|
            SRTT <- (1 - alpha) * SRTT + alpha * R'
         After the computation, a host MUST update
         RTO <- SRTT + max (G, K*RTTVAR)
```
questions:
1.  _first_est is NEVER updated to `false`. Is it correct?
2. I thoguth RTT is round-trip time and self._qd is difference of one-way delay.
    Is  `R` == `self._qd`  correct ?
3.   is `self._cto = self._srtt + max([self._qd, LEDBAT.K * self._rttvar])` correct?
I thought it corresponds to ` RTO <- SRTT + max (G, K*RTTVAR)`

**Comment by justas-** [comment]
Hi, glad to see someone reading through my code :)

Q/A:

1. No, this is not correct. It should be set to `false` after the first measurement is completed. It is up for discussion if this should be done externally (by making _first_est public) or internally by implementing some method on the lines of `Ledbat.set_observed_value(self, observed_one_way_delay)`.
2. _qd is queuing delay. From the RFC, I would guess that `R ==self._qd`
3. This is most probably not OK, as `G =/= R`.

All in all I plan to spend some time on LEDBAT implementation this or next week, but I must admit I am not 100% clear on all aspects of it.

**Comment by justas-** [comment]
I created a new project specifically for LEDBAT implementation, added a lot of fixes and placed it in its own repo: https://github.com/justas-/pyledbat
